### ISSUE TITLE
Error deploying

### ISSUE THREAD

**Issue by kluptowski** [slack-samples/deno-triage-rotation#4]
<img width="826" alt="Screenshot 2023-02-28 at 11 53 07 AM" src="https://user-images.githubusercontent.com/28935394/221922351-bd1d51a4-cd07-4085-8ca0-06b19b277e66.png">

cloned this project and tried to use slack deploy and received the error in above screenshot. all system dependencies are up to date. Am i doing something wrong?

**Comment by kluptowski** [comment]
Thank you!!! Glad it wasn’t me being dumb Kevin ***@***.*** Mar 2, 2023, at 10:34 AM, Ashley ***@***.***> wrote:﻿
Hi, @kluptowski! Thanks so much for submitting this, and apologies for the trouble you're running into to deploy this app!
I had been able to successfully deploy this a few weeks ago, so I am unsure what could've changed to cause this issue, but today I have been able to reproduce the errors you're getting when attempting to deploy with the most up-to-date system dependencies. I will take a look into this, I have a tentative solution that I will put into a PR that has gotten me past the "deploy" command.

**Comment by hello-ashleyintech** [comment]
@kluptowski - the PR that should fix this has been merged in! I recommend trying to create a new project using the template to try it out (`slack create -t slack-samples/deno-triage-rotation`), and let me know if you're still experiencing any issues with deploying!

**Comment by mm-chrisspencer** [comment]
Still having issues deploying when using only the template with no modifications, but with a different error.
```
🚫 Error: The provided manifest file does not validate against schema. Consult the additional errors field to locate specific issues (invalid_manifest)

Error Details:

1: Missing value for parameter `interactivity` (invalid_trigger_inputs)
Source: /workflows/advance_rotation/steps/0


The above errors were returned by the following Slack API method: /api/apps.manifest.validate
```

**Comment by hello-ashleyintech** [comment]
@mm-chrisspencer What version of the CLI are you using?

**Comment by mm-chrisspencer** [comment]
> @mm-chrisspencer What version of the CLI are you using? You can check using `slack version`!

@hello-ashleyintech I'm using v2.3.0, and no updates are available when checking with `slack update`. Thanks!

**Comment by hello-ashleyintech** [comment]
@mm-chrisspencer I'm going to take a look at this more in depth since I'm able to repro. Since this is a different error, could you please open a separate issue for this error using [this link](https://github.com/slack-samples/deno-triage-rotation/issues/new) and assign me to it? Thank you! 🙌
